import { StatusBar } from 'expo-status-bar';
import { StyleSheet } from 'react-native';
import { WebView } from 'react-native-webview';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import identity from './identity.json';
import html from './assets/app-html.js';

// The whole game is one inlined HTML string (generated by build.js). SafeAreaView pads the
// WebView away from the status bar / notch / nav bar natively (Android WebView does not honor
// CSS env(safe-area-inset-*), so this must be done in React Native).
export default function App() {
  const bg = identity.bgColor || '#0e1117';
  return (
    <SafeAreaProvider>
      <SafeAreaView style={[styles.container, { backgroundColor: bg }]}>
        <StatusBar style="light" backgroundColor={bg} />
        <WebView
          style={[styles.webview, { backgroundColor: bg }]}
          source={{ html }}
          originWhitelist={['*']}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          allowFileAccess={true}
          mixedContentMode="always"
          scrollEnabled={true}
          bounces={false}
          overScrollMode="never"
          showsHorizontalScrollIndicator={false}
          showsVerticalScrollIndicator={false}
        />
      </SafeAreaView>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({ container: { flex: 1 }, webview: { flex: 1 } });
