import { StatusBar } from 'expo-status-bar';
import { StyleSheet, View } from 'react-native';
import { WebView } from 'react-native-webview';
import identity from './identity.json';
import html from './assets/app-html.js';

// The whole game is one inlined HTML string (generated by build.js). We import it as a JS
// module — no asset bundling, no runtime file read — and hand it straight to the WebView.
export default function App() {
  const bg = identity.bgColor || '#0e1117';
  return (
    <View style={[styles.container, { backgroundColor: bg }]}>
      <StatusBar style="light" backgroundColor={bg} />
      <WebView
        style={[styles.webview, { backgroundColor: bg }]}
        source={{ html }}
        originWhitelist={['*']}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        allowFileAccess={true}
        mixedContentMode="always"
        scrollEnabled={true}
        bounces={false}
        overScrollMode="never"
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
      />
    </View>
  );
}

const styles = StyleSheet.create({ container: { flex: 1 }, webview: { flex: 1 } });
