/*
 * content.js (Imposter) - the built-in content library, read by the shared word engine + UI.
 *
 * Two pack TYPES feed two variants of the same game (selected by config.contentModel):
 *   type:'words'  -> "Classic / Mr. White": every Crew member shares ONE word; the Imposter
 *                    gets nothing and must fake a matching one-word clue.
 *   type:'pairs'  -> "Undercover": Crew get word A, the Imposter gets the CLOSE word B and may
 *                    not realise they differ - clues from both sides sound plausible.
 *
 * Item shorthand (normalised by the engine):
 *   'Pizza'                      a plain word (bots fall back to a generic clue)
 *   { w:'Pizza', c:['cheese'] }  a word WITH bot clue hints (humans never see `c`)
 *   { a:'Coffee', b:'Tea' }      a close pair for Undercover (b is the Imposter's word)
 *
 * `c` (clue hints) exist ONLY so offline bots can give a believable one-word clue. They are
 * never shown to humans and never enter publicState - so they cannot leak anything.
 */
(function (root, factory) {
  var C = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = C;
  if (root) root.WORD_CONTENT = C;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this), function () {
  'use strict';

  function w(id, name, category, items) { return { id: id, name: name, category: category, type: 'words', items: items }; }
  function pr(id, name, category, items) { return { id: id, name: name, category: category, type: 'pairs', items: items }; }

  var PACKS = [
    // ===================== WORD packs (Classic / Mr. White) =====================
    w('food', 'Food', 'Food & Drink', [
      { w: 'Pizza', c: ['cheese', 'slice', 'oven', 'Italian', 'pepperoni'] },
      { w: 'Sushi', c: ['rice', 'fish', 'roll', 'Japan', 'raw'] },
      { w: 'Burger', c: ['bun', 'beef', 'fries', 'grill', 'ketchup'] },
      { w: 'Pasta', c: ['noodles', 'sauce', 'Italian', 'fork', 'boil'] },
      { w: 'Tacos', c: ['shell', 'Mexican', 'salsa', 'fold', 'spicy'] },
      { w: 'Pancakes', c: ['syrup', 'breakfast', 'flip', 'stack', 'batter'] },
      { w: 'Soup', c: ['bowl', 'spoon', 'warm', 'broth', 'ladle'] },
      { w: 'Curry', c: ['spice', 'rice', 'India', 'hot', 'sauce'] },
      { w: 'Salad', c: ['leaves', 'healthy', 'bowl', 'dressing', 'green'] },
      { w: 'Steak', c: ['beef', 'grill', 'rare', 'knife', 'dinner'] },
      { w: 'Ice Cream', c: ['cold', 'cone', 'scoop', 'sweet', 'summer'] },
      { w: 'Chocolate', c: ['sweet', 'brown', 'bar', 'cocoa', 'melt'] },
      { w: 'Cheese', c: ['dairy', 'yellow', 'mouse', 'melt', 'block'] },
      { w: 'Bread', c: ['loaf', 'toast', 'bakery', 'slice', 'wheat'] },
      { w: 'Eggs', c: ['shell', 'breakfast', 'fry', 'chicken', 'yolk'] },
      { w: 'Donut', c: ['ring', 'sweet', 'glaze', 'hole', 'coffee'] },
      { w: 'Sandwich', c: ['bread', 'filling', 'lunch', 'layers', 'cut'] },
      { w: 'Noodles', c: ['slurp', 'broth', 'chopsticks', 'Asian', 'long'] },
      { w: 'Omelette', c: ['eggs', 'fold', 'pan', 'cheese', 'breakfast'] },
      { w: 'Bacon', c: ['crispy', 'pork', 'fry', 'breakfast', 'strips'] },
      { w: 'Dumplings', c: ['steam', 'filling', 'dough', 'Asian', 'bite'] },
      { w: 'Risotto', c: ['rice', 'creamy', 'stir', 'Italian', 'cheese'] },
      { w: 'Burrito', c: ['wrap', 'Mexican', 'beans', 'rice', 'fold'] },
      { w: 'Fries', c: ['potato', 'crispy', 'salt', 'ketchup', 'side'] },
      { w: 'Lasagna', c: ['layers', 'cheese', 'Italian', 'bake', 'sauce'] },
      { w: 'Cereal', c: ['milk', 'bowl', 'breakfast', 'crunch', 'flakes'] }
    ]),
    w('animals', 'Animals', 'Nature', [
      { w: 'Dog', c: ['bark', 'pet', 'loyal', 'fetch', 'tail'] },
      { w: 'Cat', c: ['meow', 'pet', 'whiskers', 'purr', 'mouse'] },
      { w: 'Lion', c: ['mane', 'roar', 'king', 'pride', 'savanna'] },
      { w: 'Elephant', c: ['trunk', 'big', 'grey', 'tusks', 'memory'] },
      { w: 'Shark', c: ['ocean', 'teeth', 'fin', 'predator', 'jaws'] },
      { w: 'Penguin', c: ['ice', 'waddle', 'tuxedo', 'cold', 'Antarctica'] },
      { w: 'Monkey', c: ['banana', 'climb', 'jungle', 'tail', 'swing'] },
      { w: 'Horse', c: ['ride', 'gallop', 'mane', 'stable', 'hooves'] },
      { w: 'Rabbit', c: ['hop', 'carrot', 'ears', 'burrow', 'fluffy'] },
      { w: 'Bear', c: ['honey', 'forest', 'hibernate', 'big', 'growl'] },
      { w: 'Snake', c: ['hiss', 'slither', 'venom', 'scales', 'coil'] },
      { w: 'Eagle', c: ['fly', 'talons', 'sky', 'beak', 'soar'] },
      { w: 'Frog', c: ['hop', 'pond', 'green', 'croak', 'lily'] },
      { w: 'Wolf', c: ['pack', 'howl', 'forest', 'moon', 'hunt'] },
      { w: 'Kangaroo', c: ['hop', 'pouch', 'Australia', 'jump', 'tail'] },
      { w: 'Owl', c: ['night', 'hoot', 'wise', 'feathers', 'eyes'] },
      { w: 'Tiger', c: ['stripes', 'wild', 'roar', 'jungle', 'orange'] },
      { w: 'Giraffe', c: ['neck', 'tall', 'spots', 'savanna', 'leaves'] },
      { w: 'Dolphin', c: ['ocean', 'swim', 'jump', 'smart', 'fins'] },
      { w: 'Crocodile', c: ['teeth', 'river', 'snap', 'reptile', 'scales'] },
      { w: 'Panda', c: ['bamboo', 'black', 'white', 'China', 'cuddly'] },
      { w: 'Fox', c: ['red', 'cunning', 'tail', 'den', 'sly'] },
      { w: 'Deer', c: ['antlers', 'forest', 'graze', 'shy', 'leap'] },
      { w: 'Whale', c: ['ocean', 'huge', 'spout', 'mammal', 'deep'] },
      { w: 'Bee', c: ['buzz', 'honey', 'sting', 'flower', 'hive'] },
      { w: 'Camel', c: ['hump', 'desert', 'sand', 'ride', 'thirst'] }
    ]),
    w('movies', 'Movies', 'Film & TV', [
      { w: 'Titanic', c: ['ship', 'iceberg', 'romance', 'sink', 'ocean'] },
      { w: 'Avatar', c: ['blue', 'aliens', 'jungle', 'Pandora', 'CGI'] },
      { w: 'Jaws', c: ['shark', 'beach', 'fear', 'boat', 'ocean'] },
      { w: 'Frozen', c: ['snow', 'sisters', 'queen', 'song', 'cold'] },
      { w: 'Gladiator', c: ['Rome', 'arena', 'sword', 'revenge', 'fight'] },
      { w: 'Rocky', c: ['boxing', 'training', 'underdog', 'stairs', 'gloves'] },
      { w: 'Up', c: ['balloons', 'house', 'old man', 'dog', 'adventure'] },
      { w: 'Shrek', c: ['ogre', 'swamp', 'donkey', 'green', 'fairytale'] },
      { w: 'Joker', c: ['clown', 'villain', 'Gotham', 'laugh', 'dark'] },
      { w: 'Batman', c: ['bat', 'Gotham', 'hero', 'cape', 'dark'] },
      { w: 'Inception', c: ['dream', 'layers', 'spinning', 'mind', 'heist'] },
      { w: 'Matrix', c: ['red pill', 'code', 'simulation', 'kung fu', 'green'] },
      { w: 'Cars', c: ['race', 'animated', 'Lightning', 'track', 'wheels'] },
      { w: 'Alien', c: ['space', 'monster', 'ship', 'horror', 'egg'] },
      { w: 'Psycho', c: ['shower', 'motel', 'thriller', 'knife', 'classic'] },
      { w: 'Grease', c: ['musical', 'cars', 'school', 'dance', 'fifties'] },
      { w: 'Coco', c: ['music', 'Mexico', 'guitar', 'family', 'spirits'] },
      { w: 'Jumanji', c: ['jungle', 'game', 'board', 'wild', 'adventure'] },
      { w: 'Ghostbusters', c: ['ghosts', 'proton', 'slime', 'green', 'team'] },
      { w: 'Moana', c: ['ocean', 'island', 'voyage', 'sea', 'song'] },
      { w: 'Aladdin', c: ['lamp', 'genie', 'carpet', 'wish', 'desert'] },
      { w: 'Twister', c: ['tornado', 'storm', 'chase', 'wind', 'disaster'] },
      { w: 'Encanto', c: ['family', 'magic', 'house', 'song', 'gifts'] },
      { w: 'Casino', c: ['Vegas', 'gamble', 'money', 'crime', 'cards'] },
      { w: 'Heat', c: ['crime', 'heist', 'cops', 'chase', 'guns'] },
      { w: 'Brave', c: ['archer', 'Scotland', 'bear', 'princess', 'forest'] }
    ]),
    w('sports', 'Sports', 'Sport', [
      { w: 'Football', c: ['goal', 'kick', 'pitch', 'team', 'ball'] },
      { w: 'Tennis', c: ['racket', 'net', 'serve', 'court', 'ace'] },
      { w: 'Boxing', c: ['gloves', 'ring', 'punch', 'rounds', 'jab'] },
      { w: 'Golf', c: ['club', 'hole', 'green', 'swing', 'putt'] },
      { w: 'Cricket', c: ['bat', 'wicket', 'over', 'pitch', 'bowl'] },
      { w: 'Swimming', c: ['pool', 'lane', 'stroke', 'water', 'dive'] },
      { w: 'Skiing', c: ['snow', 'slope', 'poles', 'mountain', 'cold'] },
      { w: 'Surfing', c: ['wave', 'board', 'ocean', 'balance', 'beach'] },
      { w: 'Cycling', c: ['bike', 'wheels', 'pedal', 'helmet', 'race'] },
      { w: 'Basketball', c: ['hoop', 'dribble', 'court', 'dunk', 'net'] },
      { w: 'Hockey', c: ['stick', 'puck', 'ice', 'goal', 'rink'] },
      { w: 'Archery', c: ['bow', 'arrow', 'target', 'aim', 'bullseye'] },
      { w: 'Bowling', c: ['pins', 'strike', 'lane', 'ball', 'roll'] },
      { w: 'Karate', c: ['belt', 'kick', 'chop', 'dojo', 'discipline'] },
      { w: 'Rowing', c: ['oars', 'boat', 'river', 'crew', 'stroke'] },
      { w: 'Darts', c: ['board', 'throw', 'bullseye', 'pub', 'aim'] },
      { w: 'Rugby', c: ['scrum', 'tackle', 'oval', 'try', 'team'] },
      { w: 'Baseball', c: ['bat', 'diamond', 'pitch', 'home run', 'glove'] },
      { w: 'Volleyball', c: ['net', 'spike', 'serve', 'beach', 'team'] },
      { w: 'Badminton', c: ['shuttle', 'racket', 'net', 'smash', 'court'] },
      { w: 'Wrestling', c: ['mat', 'pin', 'grapple', 'strong', 'hold'] },
      { w: 'Climbing', c: ['rope', 'rock', 'grip', 'height', 'harness'] },
      { w: 'Fencing', c: ['sword', 'mask', 'thrust', 'duel', 'lunge'] },
      { w: 'Gymnastics', c: ['flip', 'beam', 'vault', 'flexible', 'mat'] },
      { w: 'Snooker', c: ['cue', 'balls', 'table', 'pocket', 'green'] },
      { w: 'Skateboarding', c: ['board', 'wheels', 'tricks', 'ramp', 'ollie'] }
    ]),
    w('places', 'Places', 'Places', [
      { w: 'Beach', c: ['sand', 'waves', 'sun', 'shells', 'towel'] },
      { w: 'Hospital', c: ['doctor', 'beds', 'sick', 'nurse', 'emergency'] },
      { w: 'Airport', c: ['planes', 'gates', 'luggage', 'flight', 'security'] },
      { w: 'School', c: ['students', 'teacher', 'desk', 'lessons', 'bell'] },
      { w: 'Library', c: ['books', 'quiet', 'shelves', 'read', 'cards'] },
      { w: 'Cinema', c: ['movie', 'popcorn', 'screen', 'dark', 'seats'] },
      { w: 'Gym', c: ['weights', 'workout', 'sweat', 'machines', 'fit'] },
      { w: 'Zoo', c: ['animals', 'cages', 'visit', 'lions', 'family'] },
      { w: 'Park', c: ['grass', 'trees', 'bench', 'walk', 'picnic'] },
      { w: 'Restaurant', c: ['menu', 'waiter', 'food', 'table', 'dinner'] },
      { w: 'Museum', c: ['art', 'history', 'quiet', 'exhibit', 'old'] },
      { w: 'Bank', c: ['money', 'vault', 'teller', 'account', 'cards'] },
      { w: 'Farm', c: ['animals', 'crops', 'tractor', 'barn', 'fields'] },
      { w: 'Castle', c: ['king', 'moat', 'stone', 'old', 'tower'] },
      { w: 'Supermarket', c: ['trolley', 'aisles', 'checkout', 'food', 'shop'] },
      { w: 'Office', c: ['desk', 'meeting', 'work', 'computer', 'boss'] },
      { w: 'Church', c: ['prayer', 'bells', 'pews', 'quiet', 'cross'] },
      { w: 'Stadium', c: ['crowd', 'seats', 'match', 'cheer', 'pitch'] },
      { w: 'Prison', c: ['cells', 'bars', 'guards', 'locked', 'inmates'] },
      { w: 'Aquarium', c: ['fish', 'tank', 'glass', 'water', 'sharks'] },
      { w: 'Bakery', c: ['bread', 'cakes', 'oven', 'smell', 'fresh'] },
      { w: 'Theatre', c: ['stage', 'play', 'curtain', 'actors', 'seats'] },
      { w: 'Bridge', c: ['cross', 'river', 'span', 'arch', 'over'] },
      { w: 'Lighthouse', c: ['light', 'coast', 'tall', 'ships', 'beam'] },
      { w: 'Garage', c: ['cars', 'tools', 'park', 'fix', 'door'] },
      { w: 'Harbour', c: ['boats', 'docks', 'water', 'ships', 'pier'] }
    ]),
    w('jobs', 'Jobs', 'People & Jobs', [
      { w: 'Doctor', c: ['patients', 'hospital', 'cure', 'stethoscope', 'sick'] },
      { w: 'Teacher', c: ['students', 'school', 'lessons', 'board', 'marks'] },
      { w: 'Chef', c: ['kitchen', 'cook', 'knife', 'recipe', 'food'] },
      { w: 'Pilot', c: ['plane', 'sky', 'cockpit', 'fly', 'captain'] },
      { w: 'Farmer', c: ['crops', 'tractor', 'animals', 'field', 'harvest'] },
      { w: 'Lawyer', c: ['court', 'case', 'judge', 'suit', 'argue'] },
      { w: 'Nurse', c: ['hospital', 'care', 'patients', 'shift', 'meds'] },
      { w: 'Plumber', c: ['pipes', 'leak', 'wrench', 'water', 'fix'] },
      { w: 'Artist', c: ['paint', 'brush', 'canvas', 'gallery', 'create'] },
      { w: 'Soldier', c: ['army', 'uniform', 'duty', 'gun', 'march'] },
      { w: 'Judge', c: ['court', 'gavel', 'verdict', 'robe', 'law'] },
      { w: 'Barber', c: ['hair', 'scissors', 'cut', 'shave', 'chair'] },
      { w: 'Waiter', c: ['restaurant', 'order', 'tray', 'tip', 'menu'] },
      { w: 'Sailor', c: ['ship', 'sea', 'rope', 'deck', 'navy'] },
      { w: 'Dentist', c: ['teeth', 'drill', 'clean', 'chair', 'smile'] },
      { w: 'Firefighter', c: ['fire', 'hose', 'truck', 'rescue', 'ladder'] },
      { w: 'Scientist', c: ['lab', 'experiment', 'research', 'coat', 'discover'] },
      { w: 'Mechanic', c: ['engine', 'tools', 'fix', 'oil', 'garage'] },
      { w: 'Electrician', c: ['wires', 'power', 'fix', 'socket', 'shock'] },
      { w: 'Journalist', c: ['news', 'write', 'report', 'story', 'interview'] },
      { w: 'Photographer', c: ['camera', 'photo', 'lens', 'shoot', 'capture'] },
      { w: 'Librarian', c: ['books', 'quiet', 'shelves', 'cards', 'read'] },
      { w: 'Accountant', c: ['numbers', 'money', 'tax', 'books', 'audit'] },
      { w: 'Astronaut', c: ['space', 'rocket', 'suit', 'orbit', 'moon'] },
      { w: 'Vet', c: ['animals', 'pets', 'cure', 'clinic', 'care'] },
      { w: 'Carpenter', c: ['wood', 'saw', 'build', 'nails', 'hammer'] }
    ]),
    w('home', 'Household', 'Home', [
      { w: 'Toaster', c: ['bread', 'pop', 'kitchen', 'crumbs', 'hot'] },
      { w: 'Pillow', c: ['soft', 'bed', 'sleep', 'head', 'fluffy'] },
      { w: 'Umbrella', c: ['rain', 'open', 'wet', 'handle', 'cover'] },
      { w: 'Clock', c: ['time', 'tick', 'wall', 'hands', 'alarm'] },
      { w: 'Mirror', c: ['reflect', 'glass', 'face', 'wall', 'look'] },
      { w: 'Vacuum', c: ['clean', 'dust', 'floor', 'suck', 'carpet'] },
      { w: 'Kettle', c: ['boil', 'tea', 'water', 'steam', 'whistle'] },
      { w: 'Fridge', c: ['cold', 'food', 'kitchen', 'milk', 'door'] },
      { w: 'Lamp', c: ['light', 'bulb', 'desk', 'switch', 'glow'] },
      { w: 'Broom', c: ['sweep', 'floor', 'dust', 'handle', 'clean'] },
      { w: 'Blanket', c: ['warm', 'bed', 'cover', 'soft', 'cosy'] },
      { w: 'Candle', c: ['wax', 'flame', 'light', 'melt', 'wick'] },
      { w: 'Television', c: ['screen', 'remote', 'watch', 'shows', 'couch'] },
      { w: 'Towel', c: ['dry', 'bath', 'soft', 'wet', 'wrap'] },
      { w: 'Scissors', c: ['cut', 'paper', 'sharp', 'blades', 'craft'] },
      { w: 'Spoon', c: ['eat', 'soup', 'metal', 'stir', 'bowl'] },
      { w: 'Curtains', c: ['window', 'hang', 'draw', 'fabric', 'shade'] },
      { w: 'Carpet', c: ['floor', 'soft', 'rug', 'cover', 'vacuum'] },
      { w: 'Doorbell', c: ['ring', 'door', 'button', 'visitor', 'chime'] },
      { w: 'Bookshelf', c: ['books', 'shelves', 'wood', 'wall', 'store'] },
      { w: 'Wardrobe', c: ['clothes', 'hang', 'doors', 'bedroom', 'store'] },
      { w: 'Iron', c: ['flat', 'heat', 'clothes', 'press', 'wrinkles'] },
      { w: 'Bin', c: ['rubbish', 'waste', 'lid', 'throw', 'empty'] },
      { w: 'Sink', c: ['water', 'tap', 'wash', 'drain', 'basin'] },
      { w: 'Cushion', c: ['soft', 'sofa', 'sit', 'fluffy', 'square'] },
      { w: 'Hanger', c: ['clothes', 'hang', 'hook', 'wardrobe', 'shoulders'] }
    ]),
    w('travel', 'Travel', 'Travel', [
      { w: 'Suitcase', c: ['pack', 'wheels', 'trip', 'clothes', 'airport'] },
      { w: 'Passport', c: ['travel', 'stamp', 'photo', 'border', 'book'] },
      { w: 'Map', c: ['directions', 'fold', 'routes', 'paper', 'lost'] },
      { w: 'Hotel', c: ['room', 'bed', 'stay', 'reception', 'keys'] },
      { w: 'Train', c: ['tracks', 'station', 'carriage', 'ticket', 'rail'] },
      { w: 'Beach', c: ['sand', 'sun', 'sea', 'relax', 'waves'] },
      { w: 'Camera', c: ['photo', 'lens', 'snap', 'memory', 'click'] },
      { w: 'Backpack', c: ['straps', 'carry', 'hike', 'gear', 'shoulders'] },
      { w: 'Ticket', c: ['entry', 'price', 'seat', 'show', 'paper'] },
      { w: 'Cruise', c: ['ship', 'ocean', 'cabin', 'deck', 'sail'] },
      { w: 'Mountain', c: ['climb', 'peak', 'snow', 'high', 'hike'] },
      { w: 'Desert', c: ['sand', 'hot', 'dry', 'camel', 'dune'] },
      { w: 'Island', c: ['sea', 'palm', 'sand', 'remote', 'beach'] },
      { w: 'Taxi', c: ['fare', 'driver', 'yellow', 'ride', 'city'] },
      { w: 'Tent', c: ['camp', 'poles', 'sleep', 'outdoors', 'zip'] },
      { w: 'Compass', c: ['north', 'direction', 'needle', 'navigate', 'point'] },
      { w: 'Boarding Pass', c: ['flight', 'gate', 'scan', 'seat', 'board'] },
      { w: 'Sunscreen', c: ['sun', 'protect', 'lotion', 'beach', 'burn'] },
      { w: 'Souvenir', c: ['gift', 'memory', 'keepsake', 'shop', 'trip'] },
      { w: 'Itinerary', c: ['plan', 'schedule', 'trip', 'days', 'list'] },
      { w: 'Sunglasses', c: ['eyes', 'sun', 'shade', 'lens', 'cool'] },
      { w: 'Visa', c: ['stamp', 'border', 'permit', 'entry', 'travel'] },
      { w: 'Hostel', c: ['cheap', 'beds', 'dorm', 'backpack', 'stay'] },
      { w: 'Postcard', c: ['mail', 'photo', 'write', 'stamp', 'send'] },
      { w: 'Snorkel', c: ['sea', 'breathe', 'mask', 'swim', 'reef'] },
      { w: 'Lounge', c: ['airport', 'wait', 'relax', 'comfy', 'seats'] }
    ]),
    w('drinks', 'Drinks', 'Food & Drink', [
      { w: 'Coffee', c: ['hot', 'morning', 'beans', 'caffeine', 'mug'] },
      { w: 'Tea', c: ['hot', 'leaves', 'cup', 'brew', 'steep'] },
      { w: 'Lemonade', c: ['sour', 'sweet', 'summer', 'cold', 'citrus'] },
      { w: 'Milkshake', c: ['thick', 'sweet', 'straw', 'blend', 'cold'] },
      { w: 'Smoothie', c: ['fruit', 'blend', 'healthy', 'thick', 'cold'] },
      { w: 'Cola', c: ['fizzy', 'sweet', 'can', 'bubbles', 'dark'] },
      { w: 'Beer', c: ['alcohol', 'foam', 'pub', 'hops', 'pint'] },
      { w: 'Wine', c: ['grapes', 'glass', 'red', 'cork', 'vineyard'] },
      { w: 'Juice', c: ['fruit', 'fresh', 'sweet', 'squeeze', 'glass'] },
      { w: 'Water', c: ['clear', 'thirst', 'bottle', 'pure', 'drink'] },
      { w: 'Cocktail', c: ['mix', 'bar', 'fancy', 'shaker', 'olive'] },
      { w: 'Whiskey', c: ['strong', 'amber', 'glass', 'aged', 'barrel'] },
      { w: 'Hot Chocolate', c: ['warm', 'cocoa', 'sweet', 'winter', 'marshmallow'] },
      { w: 'Champagne', c: ['bubbly', 'celebrate', 'cork', 'fizz', 'toast'] },
      { w: 'Cider', c: ['apple', 'fizzy', 'autumn', 'pub', 'sweet'] },
      { w: 'Espresso', c: ['strong', 'small', 'shot', 'bitter', 'beans'] },
      { w: 'Latte', c: ['milk', 'coffee', 'foam', 'cafe', 'mug'] },
      { w: 'Cappuccino', c: ['foam', 'coffee', 'milk', 'cafe', 'cocoa'] },
      { w: 'Milk', c: ['white', 'cow', 'glass', 'dairy', 'pour'] },
      { w: 'Mocktail', c: ['mix', 'fruity', 'fancy', 'no alcohol', 'glass'] },
      { w: 'Iced Tea', c: ['cold', 'leaves', 'lemon', 'summer', 'sweet'] },
      { w: 'Vodka', c: ['clear', 'strong', 'shot', 'spirit', 'mix'] },
      { w: 'Rum', c: ['strong', 'amber', 'pirate', 'sugar', 'spirit'] },
      { w: 'Gin', c: ['clear', 'tonic', 'botanical', 'spirit', 'juniper'] },
      { w: 'Coconut Water', c: ['tropical', 'clear', 'refresh', 'hydrate', 'nut'] },
      { w: 'Sparkling Water', c: ['fizzy', 'clear', 'bubbles', 'refresh', 'plain'] }
    ]),
    w('desserts', 'Desserts', 'Food & Drink', [
      { w: 'Cake', c: ['sweet', 'bake', 'candles', 'frosting', 'slice'] },
      { w: 'Brownie', c: ['chocolate', 'fudge', 'square', 'gooey', 'bake'] },
      { w: 'Cookie', c: ['bake', 'chips', 'round', 'crumble', 'sweet'] },
      { w: 'Cheesecake', c: ['creamy', 'base', 'rich', 'slice', 'bake'] },
      { w: 'Pudding', c: ['spoon', 'sweet', 'bowl', 'soft', 'dessert'] },
      { w: 'Tiramisu', c: ['coffee', 'Italian', 'layers', 'cream', 'cocoa'] },
      { w: 'Muffin', c: ['bake', 'cup', 'blueberry', 'top', 'breakfast'] },
      { w: 'Pie', c: ['crust', 'filling', 'bake', 'slice', 'fruit'] },
      { w: 'Macaron', c: ['French', 'colourful', 'almond', 'small', 'crisp'] },
      { w: 'Tart', c: ['crust', 'fruit', 'glaze', 'bake', 'slice'] },
      { w: 'Cupcake', c: ['small', 'frosting', 'paper', 'sweet', 'top'] },
      { w: 'Sorbet', c: ['cold', 'fruit', 'icy', 'scoop', 'refresh'] },
      { w: 'Trifle', c: ['layers', 'cream', 'fruit', 'sponge', 'bowl'] },
      { w: 'Eclair', c: ['pastry', 'cream', 'chocolate', 'long', 'French'] },
      { w: 'Fudge', c: ['sweet', 'soft', 'sugar', 'block', 'rich'] },
      { w: 'Crumble', c: ['apple', 'oats', 'bake', 'warm', 'topping'] },
      { w: 'Doughnut', c: ['ring', 'glaze', 'sweet', 'hole', 'fried'] },
      { w: 'Pavlova', c: ['meringue', 'cream', 'fruit', 'crisp', 'soft'] },
      { w: 'Gelato', c: ['Italian', 'cold', 'creamy', 'scoop', 'sweet'] },
      { w: 'Profiterole', c: ['pastry', 'cream', 'chocolate', 'puff', 'small'] },
      { w: 'Baklava', c: ['nuts', 'honey', 'layers', 'sticky', 'pastry'] },
      { w: 'Flan', c: ['custard', 'caramel', 'wobbly', 'sweet', 'set'] },
      { w: 'Mousse', c: ['airy', 'chocolate', 'whip', 'light', 'spoon'] },
      { w: 'Toffee', c: ['sticky', 'sweet', 'chewy', 'sugar', 'hard'] },
      { w: 'Banana Split', c: ['banana', 'scoops', 'cream', 'cherry', 'sundae'] },
      { w: 'Jelly', c: ['wobbly', 'sweet', 'fruity', 'set', 'spoon'] }
    ]),
    w('tech', 'Tech & Gadgets', 'Technology', [
      { w: 'Laptop', c: ['screen', 'keyboard', 'portable', 'work', 'charge'] },
      { w: 'Smartphone', c: ['screen', 'apps', 'call', 'touch', 'pocket'] },
      { w: 'Headphones', c: ['ears', 'music', 'sound', 'wireless', 'volume'] },
      { w: 'Camera', c: ['photo', 'lens', 'snap', 'zoom', 'flash'] },
      { w: 'Drone', c: ['fly', 'remote', 'camera', 'propeller', 'sky'] },
      { w: 'Tablet', c: ['screen', 'touch', 'apps', 'flat', 'portable'] },
      { w: 'Console', c: ['games', 'controller', 'play', 'screen', 'TV'] },
      { w: 'Smartwatch', c: ['wrist', 'steps', 'screen', 'notify', 'time'] },
      { w: 'Speaker', c: ['sound', 'music', 'volume', 'bass', 'wireless'] },
      { w: 'Keyboard', c: ['keys', 'type', 'letters', 'desk', 'click'] },
      { w: 'Mouse', c: ['click', 'cursor', 'scroll', 'desk', 'pointer'] },
      { w: 'Printer', c: ['paper', 'ink', 'print', 'office', 'page'] },
      { w: 'Router', c: ['wifi', 'internet', 'signal', 'connect', 'box'] },
      { w: 'Charger', c: ['power', 'cable', 'plug', 'battery', 'socket'] },
      { w: 'Monitor', c: ['screen', 'display', 'desk', 'pixels', 'view'] },
      { w: 'Microphone', c: ['voice', 'record', 'sound', 'sing', 'audio'] },
      { w: 'Webcam', c: ['video', 'call', 'lens', 'stream', 'desk'] },
      { w: 'Projector', c: ['screen', 'light', 'slides', 'beam', 'wall'] },
      { w: 'Scanner', c: ['copy', 'document', 'glass', 'image', 'digitise'] },
      { w: 'Power Bank', c: ['battery', 'charge', 'portable', 'phone', 'cable'] },
      { w: 'Earbuds', c: ['ears', 'tiny', 'wireless', 'music', 'pods'] },
      { w: 'Modem', c: ['internet', 'connect', 'signal', 'box', 'cable'] },
      { w: 'Hard Drive', c: ['storage', 'data', 'files', 'backup', 'disk'] },
      { w: 'Calculator', c: ['numbers', 'math', 'buttons', 'sum', 'screen'] },
      { w: 'Thermostat', c: ['heat', 'temperature', 'dial', 'control', 'home'] },
      { w: 'VR Headset', c: ['virtual', 'eyes', 'immerse', 'game', 'wear'] }
    ]),
    w('music', 'Music & Instruments', 'Music', [
      { w: 'Guitar', c: ['strings', 'strum', 'chords', 'pick', 'band'] },
      { w: 'Piano', c: ['keys', 'black', 'white', 'play', 'pedal'] },
      { w: 'Drums', c: ['beat', 'sticks', 'rhythm', 'loud', 'kit'] },
      { w: 'Violin', c: ['strings', 'bow', 'classical', 'chin', 'orchestra'] },
      { w: 'Flute', c: ['blow', 'holes', 'metal', 'high', 'wind'] },
      { w: 'Trumpet', c: ['brass', 'blow', 'valves', 'loud', 'jazz'] },
      { w: 'Saxophone', c: ['brass', 'jazz', 'reed', 'curve', 'blow'] },
      { w: 'Harp', c: ['strings', 'pluck', 'large', 'angel', 'gentle'] },
      { w: 'Cello', c: ['strings', 'bow', 'large', 'low', 'orchestra'] },
      { w: 'Trombone', c: ['brass', 'slide', 'blow', 'low', 'band'] },
      { w: 'Accordion', c: ['squeeze', 'keys', 'bellows', 'folk', 'buttons'] },
      { w: 'Banjo', c: ['strings', 'twang', 'country', 'pluck', 'round'] },
      { w: 'Tambourine', c: ['shake', 'jingle', 'rhythm', 'hand', 'round'] },
      { w: 'Xylophone', c: ['bars', 'mallets', 'tune', 'tap', 'wood'] },
      { w: 'Clarinet', c: ['reed', 'blow', 'black', 'wind', 'keys'] },
      { w: 'Microphone', c: ['sing', 'voice', 'stage', 'amplify', 'stand'] },
      { w: 'Ukulele', c: ['strings', 'small', 'strum', 'Hawaii', 'pluck'] },
      { w: 'Bagpipes', c: ['Scotland', 'blow', 'drone', 'kilt', 'wail'] },
      { w: 'Organ', c: ['keys', 'pipes', 'church', 'pedals', 'loud'] },
      { w: 'Bongos', c: ['drums', 'hands', 'pair', 'tap', 'rhythm'] },
      { w: 'Mandolin', c: ['strings', 'pluck', 'small', 'folk', 'round'] },
      { w: 'Oboe', c: ['reed', 'blow', 'wind', 'orchestra', 'thin'] },
      { w: 'Triangle', c: ['metal', 'ting', 'beat', 'small', 'hang'] },
      { w: 'Synthesizer', c: ['keys', 'electronic', 'sounds', 'play', 'buttons'] },
      { w: 'Cymbals', c: ['crash', 'metal', 'loud', 'clash', 'drums'] },
      { w: 'Maracas', c: ['shake', 'rattle', 'pair', 'rhythm', 'beads'] }
    ]),
    w('clothing', 'Clothing', 'Fashion', [
      { w: 'Jacket', c: ['warm', 'zip', 'sleeves', 'outer', 'wear'] },
      { w: 'Jeans', c: ['denim', 'legs', 'blue', 'pockets', 'casual'] },
      { w: 'Sweater', c: ['warm', 'wool', 'cosy', 'knit', 'winter'] },
      { w: 'Dress', c: ['elegant', 'wear', 'formal', 'fabric', 'flowing'] },
      { w: 'Hat', c: ['head', 'brim', 'cover', 'sun', 'wear'] },
      { w: 'Scarf', c: ['neck', 'warm', 'wrap', 'winter', 'wool'] },
      { w: 'Gloves', c: ['hands', 'warm', 'fingers', 'winter', 'pair'] },
      { w: 'Socks', c: ['feet', 'pair', 'warm', 'cotton', 'shoes'] },
      { w: 'Shirt', c: ['buttons', 'collar', 'sleeves', 'wear', 'cotton'] },
      { w: 'Skirt', c: ['waist', 'flowing', 'wear', 'fabric', 'hem'] },
      { w: 'Boots', c: ['feet', 'leather', 'laces', 'walk', 'tall'] },
      { w: 'Coat', c: ['warm', 'long', 'winter', 'buttons', 'outer'] },
      { w: 'Tie', c: ['neck', 'formal', 'knot', 'suit', 'collar'] },
      { w: 'Belt', c: ['waist', 'buckle', 'leather', 'hold', 'loop'] },
      { w: 'Shorts', c: ['legs', 'summer', 'casual', 'short', 'wear'] },
      { w: 'Pyjamas', c: ['sleep', 'bed', 'cosy', 'night', 'soft'] },
      { w: 'Hoodie', c: ['hood', 'casual', 'warm', 'pocket', 'cotton'] },
      { w: 'Blazer', c: ['smart', 'jacket', 'formal', 'buttons', 'work'] },
      { w: 'Cardigan', c: ['knit', 'buttons', 'warm', 'cosy', 'wool'] },
      { w: 'Sandals', c: ['feet', 'summer', 'straps', 'open', 'beach'] },
      { w: 'Sneakers', c: ['feet', 'sport', 'laces', 'comfy', 'run'] },
      { w: 'Cap', c: ['head', 'brim', 'casual', 'sun', 'baseball'] },
      { w: 'Vest', c: ['sleeveless', 'wear', 'layer', 'top', 'warm'] },
      { w: 'Leggings', c: ['legs', 'tight', 'stretch', 'wear', 'gym'] },
      { w: 'Overalls', c: ['straps', 'work', 'denim', 'pockets', 'pants'] },
      { w: 'Bikini', c: ['beach', 'swim', 'summer', 'two piece', 'pool'] }
    ]),
    w('vehicles', 'Vehicles', 'Transport', [
      { w: 'Car', c: ['drive', 'wheels', 'road', 'engine', 'doors'] },
      { w: 'Bicycle', c: ['pedal', 'wheels', 'ride', 'chain', 'handlebars'] },
      { w: 'Motorcycle', c: ['ride', 'engine', 'fast', 'helmet', 'two wheels'] },
      { w: 'Bus', c: ['passengers', 'route', 'stop', 'big', 'driver'] },
      { w: 'Train', c: ['tracks', 'rail', 'carriage', 'station', 'fast'] },
      { w: 'Airplane', c: ['fly', 'wings', 'sky', 'pilot', 'jet'] },
      { w: 'Helicopter', c: ['rotor', 'fly', 'hover', 'blades', 'sky'] },
      { w: 'Boat', c: ['water', 'sail', 'float', 'deck', 'river'] },
      { w: 'Truck', c: ['cargo', 'big', 'road', 'haul', 'wheels'] },
      { w: 'Submarine', c: ['underwater', 'dive', 'sonar', 'navy', 'deep'] },
      { w: 'Tractor', c: ['farm', 'field', 'big wheels', 'plough', 'slow'] },
      { w: 'Scooter', c: ['ride', 'small', 'kick', 'wheels', 'fold'] },
      { w: 'Van', c: ['cargo', 'deliver', 'big', 'doors', 'road'] },
      { w: 'Ferry', c: ['water', 'cars', 'cross', 'deck', 'sail'] },
      { w: 'Rocket', c: ['space', 'launch', 'fast', 'fuel', 'sky'] },
      { w: 'Tram', c: ['rails', 'city', 'electric', 'street', 'stop'] },
      { w: 'Taxi', c: ['fare', 'driver', 'yellow', 'city', 'ride'] },
      { w: 'Ambulance', c: ['siren', 'rescue', 'hospital', 'fast', 'medic'] },
      { w: 'Jet Ski', c: ['water', 'fast', 'splash', 'ride', 'sea'] },
      { w: 'Yacht', c: ['luxury', 'sail', 'sea', 'rich', 'deck'] },
      { w: 'Caravan', c: ['tow', 'holiday', 'sleep', 'wheels', 'camp'] },
      { w: 'Canoe', c: ['paddle', 'river', 'narrow', 'water', 'tip'] },
      { w: 'Forklift', c: ['lift', 'warehouse', 'load', 'pallet', 'prongs'] },
      { w: 'Hot Air Balloon', c: ['float', 'sky', 'basket', 'fire', 'drift'] },
      { w: 'Sled', c: ['snow', 'slide', 'winter', 'pull', 'hill'] },
      { w: 'Gondola', c: ['Venice', 'pole', 'canal', 'narrow', 'row'] }
    ]),
    w('mythical', 'Mythical Creatures', 'Fantasy', [
      { w: 'Dragon', c: ['fire', 'wings', 'scales', 'fierce', 'cave'] },
      { w: 'Unicorn', c: ['horn', 'horse', 'magic', 'white', 'rainbow'] },
      { w: 'Mermaid', c: ['tail', 'sea', 'sing', 'fish', 'ocean'] },
      { w: 'Phoenix', c: ['fire', 'rebirth', 'wings', 'ashes', 'flame'] },
      { w: 'Griffin', c: ['eagle', 'lion', 'wings', 'beak', 'fierce'] },
      { w: 'Centaur', c: ['horse', 'human', 'half', 'bow', 'gallop'] },
      { w: 'Werewolf', c: ['moon', 'howl', 'fur', 'fangs', 'transform'] },
      { w: 'Vampire', c: ['fangs', 'blood', 'night', 'bat', 'cape'] },
      { w: 'Goblin', c: ['small', 'green', 'sneaky', 'cave', 'ugly'] },
      { w: 'Troll', c: ['bridge', 'big', 'ugly', 'grumpy', 'cave'] },
      { w: 'Fairy', c: ['wings', 'tiny', 'magic', 'dust', 'flower'] },
      { w: 'Giant', c: ['huge', 'tall', 'strong', 'stomp', 'beanstalk'] },
      { w: 'Yeti', c: ['snow', 'fur', 'mountain', 'big', 'cold'] },
      { w: 'Kraken', c: ['ocean', 'tentacles', 'deep', 'ships', 'monster'] },
      { w: 'Minotaur', c: ['bull', 'maze', 'horns', 'half', 'fierce'] },
      { w: 'Pegasus', c: ['horse', 'wings', 'fly', 'white', 'sky'] },
      { w: 'Zombie', c: ['undead', 'brains', 'shuffle', 'rot', 'horde'] },
      { w: 'Genie', c: ['lamp', 'wish', 'magic', 'smoke', 'grant'] },
      { w: 'Cyclops', c: ['one eye', 'giant', 'cave', 'huge', 'club'] },
      { w: 'Banshee', c: ['scream', 'ghost', 'wail', 'omen', 'spirit'] },
      { w: 'Hydra', c: ['heads', 'serpent', 'many', 'water', 'regrow'] },
      { w: 'Elf', c: ['ears', 'forest', 'graceful', 'bow', 'magic'] },
      { w: 'Sphinx', c: ['riddle', 'lion', 'desert', 'wings', 'guard'] },
      { w: 'Gargoyle', c: ['stone', 'roof', 'wings', 'guard', 'carved'] },
      { w: 'Ghost', c: ['spooky', 'white', 'haunt', 'float', 'boo'] },
      { w: 'Imp', c: ['small', 'mischief', 'demon', 'tail', 'horns'] }
    ]),
    w('kitchen', 'Kitchen', 'Home', [
      { w: 'Knife', c: ['sharp', 'cut', 'blade', 'chop', 'handle'] },
      { w: 'Fork', c: ['prongs', 'eat', 'metal', 'stab', 'plate'] },
      { w: 'Plate', c: ['round', 'food', 'flat', 'serve', 'wash'] },
      { w: 'Pan', c: ['fry', 'stove', 'handle', 'cook', 'flat'] },
      { w: 'Pot', c: ['boil', 'soup', 'stove', 'lid', 'cook'] },
      { w: 'Whisk', c: ['mix', 'beat', 'eggs', 'wire', 'stir'] },
      { w: 'Blender', c: ['mix', 'smoothie', 'spin', 'blade', 'jug'] },
      { w: 'Oven', c: ['bake', 'hot', 'roast', 'door', 'heat'] },
      { w: 'Microwave', c: ['heat', 'reheat', 'beep', 'door', 'spin'] },
      { w: 'Grater', c: ['cheese', 'shred', 'sharp', 'metal', 'rub'] },
      { w: 'Ladle', c: ['soup', 'scoop', 'serve', 'long', 'spoon'] },
      { w: 'Colander', c: ['drain', 'holes', 'pasta', 'rinse', 'bowl'] },
      { w: 'Rolling Pin', c: ['dough', 'roll', 'flat', 'bake', 'wood'] },
      { w: 'Spatula', c: ['flip', 'flat', 'pan', 'lift', 'handle'] },
      { w: 'Cutting Board', c: ['chop', 'wood', 'surface', 'knife', 'prep'] },
      { w: 'Tongs', c: ['grip', 'grab', 'turn', 'pair', 'serve'] },
      { w: 'Peeler', c: ['skin', 'potato', 'blade', 'strip', 'veg'] },
      { w: 'Sieve', c: ['flour', 'mesh', 'sift', 'drain', 'fine'] },
      { w: 'Measuring Cup', c: ['measure', 'pour', 'recipe', 'lines', 'amount'] },
      { w: 'Corkscrew', c: ['wine', 'cork', 'twist', 'open', 'pull'] },
      { w: 'Toaster', c: ['bread', 'pop', 'crisp', 'slots', 'heat'] },
      { w: 'Mixing Bowl', c: ['mix', 'batter', 'large', 'stir', 'round'] },
      { w: 'Saucepan', c: ['boil', 'handle', 'stove', 'sauce', 'lid'] },
      { w: 'Chopsticks', c: ['pair', 'Asian', 'pick', 'rice', 'sticks'] },
      { w: 'Apron', c: ['cook', 'tie', 'protect', 'wear', 'splash'] },
      { w: 'Timer', c: ['count', 'beep', 'minutes', 'set', 'ring'] }
    ]),

    // ===================== PAIR packs (Undercover variant) ======================
    // Crew get A; the Imposter gets the close word B. Clue hints suit BOTH so bots blend in.
    pr('pairs_food', 'Food (pairs)', 'Food & Drink', [
      { a: 'Coffee', b: 'Tea', c: ['hot', 'morning', 'cup', 'drink'] },
      { a: 'Pizza', b: 'Burger', c: ['fast food', 'cheese', 'takeaway', 'dinner'] },
      { a: 'Cake', b: 'Pie', c: ['sweet', 'bake', 'slice', 'dessert'] },
      { a: 'Ice Cream', b: 'Yoghurt', c: ['cold', 'creamy', 'spoon', 'sweet'] },
      { a: 'Beer', b: 'Wine', c: ['alcohol', 'glass', 'bar', 'drink'] },
      { a: 'Apple', b: 'Pear', c: ['fruit', 'tree', 'crunch', 'healthy'] },
      { a: 'Pasta', b: 'Noodles', c: ['boil', 'sauce', 'long', 'fork'] },
      { a: 'Pancake', b: 'Waffle', c: ['breakfast', 'syrup', 'batter', 'sweet'] },
      { a: 'Soup', b: 'Stew', c: ['warm', 'bowl', 'spoon', 'broth'] },
      { a: 'Jam', b: 'Marmalade', c: ['fruit', 'spread', 'sweet', 'toast'] },
      { a: 'Taco', b: 'Burrito', c: ['Mexican', 'wrap', 'beans', 'spicy'] },
      { a: 'Biscuit', b: 'Cracker', c: ['crisp', 'snack', 'bite', 'dry'] },
      { a: 'Sausage', b: 'Hot Dog', c: ['meat', 'grill', 'long', 'bun'] }
    ]),
    pr('pairs_animals', 'Animals (pairs)', 'Nature', [
      { a: 'Cat', b: 'Dog', c: ['pet', 'fur', 'home', 'cute'] },
      { a: 'Lion', b: 'Tiger', c: ['big cat', 'wild', 'roar', 'predator'] },
      { a: 'Dolphin', b: 'Whale', c: ['ocean', 'swim', 'mammal', 'big'] },
      { a: 'Frog', b: 'Toad', c: ['hop', 'pond', 'green', 'amphibian'] },
      { a: 'Crocodile', b: 'Alligator', c: ['teeth', 'water', 'reptile', 'snap'] },
      { a: 'Rabbit', b: 'Hare', c: ['hop', 'ears', 'fast', 'fields'] },
      { a: 'Moth', b: 'Butterfly', c: ['wings', 'fly', 'flutter', 'insect'] },
      { a: 'Donkey', b: 'Horse', c: ['ride', 'farm', 'hooves', 'animal'] },
      { a: 'Leopard', b: 'Cheetah', c: ['spots', 'fast', 'wild', 'cat'] },
      { a: 'Turtle', b: 'Tortoise', c: ['shell', 'slow', 'reptile', 'legs'] },
      { a: 'Seal', b: 'Sea Lion', c: ['ocean', 'flippers', 'bark', 'swim'] },
      { a: 'Crow', b: 'Raven', c: ['black', 'bird', 'caw', 'fly'] },
      { a: 'Goat', b: 'Sheep', c: ['farm', 'graze', 'wool', 'hooves'] }
    ]),
    pr('pairs_everyday', 'Everyday (pairs)', 'Home', [
      { a: 'Pen', b: 'Pencil', c: ['write', 'paper', 'hand', 'school'] },
      { a: 'Sofa', b: 'Armchair', c: ['sit', 'comfy', 'living room', 'cushion'] },
      { a: 'Phone', b: 'Tablet', c: ['screen', 'apps', 'touch', 'charge'] },
      { a: 'Cup', b: 'Mug', c: ['drink', 'handle', 'hot', 'kitchen'] },
      { a: 'Shoe', b: 'Boot', c: ['feet', 'wear', 'laces', 'walk'] },
      { a: 'Window', b: 'Door', c: ['house', 'open', 'wall', 'glass'] },
      { a: 'Clock', b: 'Watch', c: ['time', 'hands', 'tick', 'hours'] },
      { a: 'Towel', b: 'Blanket', c: ['cloth', 'soft', 'fold', 'warm'] },
      { a: 'Bowl', b: 'Plate', c: ['food', 'dish', 'serve', 'round'] },
      { a: 'Broom', b: 'Mop', c: ['floor', 'clean', 'handle', 'sweep'] },
      { a: 'Lamp', b: 'Candle', c: ['light', 'glow', 'dark', 'room'] },
      { a: 'Carpet', b: 'Rug', c: ['floor', 'soft', 'cover', 'woven'] },
      { a: 'Curtain', b: 'Blind', c: ['window', 'cover', 'shade', 'pull'] }
    ]),
    pr('pairs_places', 'Places (pairs)', 'Places', [
      { a: 'Sea', b: 'Lake', c: ['water', 'swim', 'shore', 'blue'] },
      { a: 'Mountain', b: 'Hill', c: ['high', 'climb', 'view', 'walk'] },
      { a: 'Cinema', b: 'Theatre', c: ['show', 'seats', 'stage', 'tickets'] },
      { a: 'Cafe', b: 'Restaurant', c: ['eat', 'menu', 'table', 'order'] },
      { a: 'School', b: 'University', c: ['study', 'students', 'classes', 'exams'] },
      { a: 'Hotel', b: 'Hostel', c: ['stay', 'beds', 'travel', 'rooms'] },
      { a: 'River', b: 'Canal', c: ['water', 'flow', 'boat', 'bank'] },
      { a: 'Park', b: 'Garden', c: ['grass', 'plants', 'green', 'outside'] },
      { a: 'Airport', b: 'Station', c: ['travel', 'platform', 'tickets', 'wait'] },
      { a: 'Bar', b: 'Pub', c: ['drinks', 'stool', 'beer', 'social'] },
      { a: 'Museum', b: 'Gallery', c: ['art', 'exhibit', 'quiet', 'visit'] },
      { a: 'Beach', b: 'Coast', c: ['sea', 'sand', 'waves', 'shore'] },
      { a: 'Village', b: 'Town', c: ['houses', 'people', 'streets', 'local'] }
    ]),
    pr('pairs_drinks', 'Drinks (pairs)', 'Food & Drink', [
      { a: 'Coffee', b: 'Tea', c: ['hot', 'morning', 'cup', 'brew'] },
      { a: 'Beer', b: 'Cider', c: ['alcohol', 'pub', 'fizzy', 'pint'] },
      { a: 'Wine', b: 'Champagne', c: ['grapes', 'glass', 'toast', 'fancy'] },
      { a: 'Juice', b: 'Smoothie', c: ['fruit', 'fresh', 'glass', 'sweet'] },
      { a: 'Cola', b: 'Lemonade', c: ['fizzy', 'sweet', 'cold', 'bubbles'] },
      { a: 'Milkshake', b: 'Smoothie', c: ['thick', 'blend', 'straw', 'cold'] },
      { a: 'Whiskey', b: 'Brandy', c: ['strong', 'amber', 'glass', 'aged'] },
      { a: 'Espresso', b: 'Cappuccino', c: ['coffee', 'beans', 'hot', 'cafe'] },
      { a: 'Vodka', b: 'Gin', c: ['clear', 'strong', 'spirit', 'mix'] },
      { a: 'Rum', b: 'Whiskey', c: ['strong', 'amber', 'spirit', 'glass'] },
      { a: 'Latte', b: 'Cappuccino', c: ['milk', 'coffee', 'foam', 'cafe'] },
      { a: 'Milk', b: 'Cream', c: ['white', 'dairy', 'pour', 'rich'] },
      { a: 'Cola', b: 'Root Beer', c: ['fizzy', 'sweet', 'dark', 'bubbles'] }
    ]),
    pr('pairs_sport', 'Sport (pairs)', 'Sport', [
      { a: 'Football', b: 'Rugby', c: ['team', 'ball', 'pitch', 'tackle'] },
      { a: 'Tennis', b: 'Squash', c: ['racket', 'court', 'serve', 'rally'] },
      { a: 'Skiing', b: 'Snowboarding', c: ['snow', 'slope', 'mountain', 'cold'] },
      { a: 'Boxing', b: 'Wrestling', c: ['fight', 'ring', 'rounds', 'strong'] },
      { a: 'Swimming', b: 'Diving', c: ['pool', 'water', 'splash', 'wet'] },
      { a: 'Baseball', b: 'Cricket', c: ['bat', 'ball', 'pitch', 'field'] },
      { a: 'Cycling', b: 'Motorsport', c: ['wheels', 'race', 'speed', 'track'] },
      { a: 'Hockey', b: 'Lacrosse', c: ['stick', 'goal', 'team', 'field'] },
      { a: 'Golf', b: 'Croquet', c: ['ball', 'club', 'green', 'hole'] },
      { a: 'Basketball', b: 'Netball', c: ['hoop', 'pass', 'court', 'team'] },
      { a: 'Karate', b: 'Judo', c: ['belt', 'throw', 'dojo', 'fight'] },
      { a: 'Surfing', b: 'Bodyboarding', c: ['wave', 'board', 'ocean', 'ride'] },
      { a: 'Badminton', b: 'Tennis', c: ['racket', 'net', 'court', 'serve'] }
    ]),
    pr('pairs_tech', 'Tech (pairs)', 'Technology', [
      { a: 'Laptop', b: 'Tablet', c: ['screen', 'portable', 'charge', 'apps'] },
      { a: 'Phone', b: 'Smartwatch', c: ['screen', 'notify', 'charge', 'pocket'] },
      { a: 'Headphones', b: 'Earbuds', c: ['ears', 'music', 'sound', 'wireless'] },
      { a: 'Camera', b: 'Camcorder', c: ['lens', 'record', 'zoom', 'capture'] },
      { a: 'Keyboard', b: 'Keypad', c: ['keys', 'type', 'press', 'buttons'] },
      { a: 'Speaker', b: 'Soundbar', c: ['sound', 'music', 'volume', 'bass'] },
      { a: 'Monitor', b: 'Television', c: ['screen', 'display', 'pixels', 'view'] },
      { a: 'Router', b: 'Modem', c: ['internet', 'signal', 'connect', 'box'] },
      { a: 'Mouse', b: 'Trackpad', c: ['click', 'cursor', 'point', 'scroll'] },
      { a: 'Charger', b: 'Power Bank', c: ['battery', 'power', 'cable', 'charge'] },
      { a: 'Drone', b: 'Helicopter', c: ['fly', 'rotor', 'hover', 'sky'] },
      { a: 'Microphone', b: 'Webcam', c: ['record', 'capture', 'call', 'desk'] },
      { a: 'Printer', b: 'Scanner', c: ['paper', 'office', 'document', 'glass'] }
    ]),
    pr('pairs_nature', 'Nature (pairs)', 'Nature', [
      { a: 'River', b: 'Stream', c: ['water', 'flow', 'bank', 'fish'] },
      { a: 'Forest', b: 'Jungle', c: ['trees', 'green', 'wild', 'leaves'] },
      { a: 'Hill', b: 'Mountain', c: ['high', 'climb', 'slope', 'view'] },
      { a: 'Lake', b: 'Pond', c: ['water', 'still', 'fish', 'shore'] },
      { a: 'Storm', b: 'Hurricane', c: ['wind', 'rain', 'clouds', 'wild'] },
      { a: 'Rock', b: 'Boulder', c: ['stone', 'hard', 'ground', 'grey'] },
      { a: 'Meadow', b: 'Prairie', c: ['grass', 'flat', 'open', 'flowers'] },
      { a: 'Valley', b: 'Canyon', c: ['low', 'between', 'cliffs', 'deep'] },
      { a: 'Fog', b: 'Mist', c: ['cloud', 'damp', 'hazy', 'low'] },
      { a: 'Cave', b: 'Tunnel', c: ['dark', 'underground', 'hollow', 'echo'] },
      { a: 'Island', b: 'Peninsula', c: ['land', 'water', 'shore', 'sea'] },
      { a: 'Glacier', b: 'Iceberg', c: ['ice', 'cold', 'frozen', 'huge'] },
      { a: 'Swamp', b: 'Marsh', c: ['wet', 'mud', 'reeds', 'soggy'] }
    ]),

    // ===================== NEW WORD packs =====================
    w('bodyparts', 'Body', 'Body', [
      { w: 'Hand', c: ['fingers', 'palm', 'grip', 'wave', 'shake'] },
      { w: 'Foot', c: ['toes', 'walk', 'sole', 'kick', 'shoe'] },
      { w: 'Nose', c: ['smell', 'breathe', 'face', 'sniff', 'centre'] },
      { w: 'Ear', c: ['hear', 'listen', 'side', 'sound', 'lobe'] },
      { w: 'Eye', c: ['see', 'blink', 'pupil', 'lashes', 'colour'] },
      { w: 'Mouth', c: ['speak', 'eat', 'lips', 'teeth', 'taste'] },
      { w: 'Knee', c: ['bend', 'leg', 'joint', 'kneel', 'cap'] },
      { w: 'Elbow', c: ['arm', 'bend', 'joint', 'point', 'lean'] },
      { w: 'Shoulder', c: ['arm', 'carry', 'broad', 'shrug', 'top'] },
      { w: 'Heart', c: ['beat', 'pump', 'blood', 'chest', 'love'] },
      { w: 'Brain', c: ['think', 'mind', 'skull', 'smart', 'nerves'] },
      { w: 'Tongue', c: ['taste', 'lick', 'mouth', 'speak', 'pink'] },
      { w: 'Hair', c: ['head', 'grow', 'comb', 'cut', 'strands'] },
      { w: 'Tooth', c: ['bite', 'chew', 'white', 'mouth', 'enamel'] },
      { w: 'Finger', c: ['hand', 'point', 'ring', 'nail', 'touch'] },
      { w: 'Stomach', c: ['belly', 'digest', 'full', 'tummy', 'food'] },
      { w: 'Lungs', c: ['breathe', 'air', 'chest', 'oxygen', 'pair'] },
      { w: 'Spine', c: ['back', 'bones', 'straight', 'column', 'support'] },
      { w: 'Wrist', c: ['hand', 'arm', 'joint', 'watch', 'bend'] },
      { w: 'Ankle', c: ['foot', 'leg', 'joint', 'twist', 'low'] },
      { w: 'Neck', c: ['head', 'turn', 'collar', 'throat', 'support'] },
      { w: 'Chin', c: ['face', 'jaw', 'below', 'point', 'beard'] },
      { w: 'Cheek', c: ['face', 'blush', 'soft', 'side', 'kiss'] },
      { w: 'Liver', c: ['organ', 'filter', 'belly', 'detox', 'large'] }
    ]),
    w('weather', 'Weather & Nature', 'Weather & Nature', [
      { w: 'Rain', c: ['wet', 'drops', 'umbrella', 'clouds', 'puddle'] },
      { w: 'Snow', c: ['white', 'cold', 'flakes', 'winter', 'soft'] },
      { w: 'Thunder', c: ['loud', 'storm', 'rumble', 'boom', 'sky'] },
      { w: 'Lightning', c: ['flash', 'bolt', 'storm', 'strike', 'bright'] },
      { w: 'Rainbow', c: ['colours', 'arc', 'sky', 'rain', 'sun'] },
      { w: 'Wind', c: ['blow', 'gust', 'breeze', 'air', 'cool'] },
      { w: 'Cloud', c: ['sky', 'fluffy', 'grey', 'float', 'rain'] },
      { w: 'Sun', c: ['hot', 'bright', 'day', 'shine', 'yellow'] },
      { w: 'Fog', c: ['hazy', 'damp', 'thick', 'low', 'grey'] },
      { w: 'Hail', c: ['ice', 'pellets', 'storm', 'hard', 'fall'] },
      { w: 'Frost', c: ['cold', 'white', 'morning', 'crisp', 'freeze'] },
      { w: 'Storm', c: ['wind', 'rain', 'wild', 'dark', 'clouds'] },
      { w: 'Tornado', c: ['twist', 'wind', 'funnel', 'spin', 'destroy'] },
      { w: 'Drought', c: ['dry', 'no rain', 'cracked', 'hot', 'thirst'] },
      { w: 'Flood', c: ['water', 'overflow', 'rising', 'wet', 'rain'] },
      { w: 'Heatwave', c: ['hot', 'sweat', 'summer', 'intense', 'sun'] },
      { w: 'Breeze', c: ['gentle', 'wind', 'cool', 'soft', 'air'] },
      { w: 'Dew', c: ['drops', 'morning', 'grass', 'wet', 'fresh'] },
      { w: 'Sunset', c: ['evening', 'orange', 'horizon', 'sky', 'dusk'] },
      { w: 'Sunrise', c: ['morning', 'dawn', 'glow', 'horizon', 'early'] },
      { w: 'Avalanche', c: ['snow', 'slide', 'mountain', 'rush', 'cold'] },
      { w: 'Earthquake', c: ['shake', 'ground', 'tremor', 'crack', 'rumble'] },
      { w: 'Volcano', c: ['lava', 'erupt', 'mountain', 'ash', 'hot'] },
      { w: 'Tsunami', c: ['wave', 'ocean', 'huge', 'flood', 'coast'] }
    ]),
    w('space', 'Space', 'Space', [
      { w: 'Moon', c: ['night', 'crater', 'orbit', 'glow', 'phases'] },
      { w: 'Sun', c: ['star', 'hot', 'bright', 'centre', 'shine'] },
      { w: 'Star', c: ['twinkle', 'night', 'shine', 'far', 'sky'] },
      { w: 'Planet', c: ['orbit', 'round', 'space', 'gravity', 'sphere'] },
      { w: 'Comet', c: ['tail', 'ice', 'streak', 'orbit', 'fast'] },
      { w: 'Asteroid', c: ['rock', 'belt', 'space', 'float', 'small'] },
      { w: 'Galaxy', c: ['stars', 'spiral', 'vast', 'space', 'milky'] },
      { w: 'Rocket', c: ['launch', 'fuel', 'fast', 'space', 'blast'] },
      { w: 'Astronaut', c: ['suit', 'space', 'float', 'helmet', 'mission'] },
      { w: 'Satellite', c: ['orbit', 'signal', 'space', 'dish', 'circle'] },
      { w: 'Telescope', c: ['look', 'stars', 'lens', 'zoom', 'sky'] },
      { w: 'Meteor', c: ['streak', 'fall', 'bright', 'sky', 'flash'] },
      { w: 'Eclipse', c: ['shadow', 'dark', 'align', 'rare', 'sun'] },
      { w: 'Orbit', c: ['circle', 'path', 'around', 'loop', 'space'] },
      { w: 'Nebula', c: ['cloud', 'gas', 'colour', 'space', 'glow'] },
      { w: 'Black Hole', c: ['pull', 'dark', 'gravity', 'collapse', 'vast'] },
      { w: 'Spacesuit', c: ['wear', 'oxygen', 'helmet', 'bulky', 'protect'] },
      { w: 'Mars', c: ['red', 'planet', 'rover', 'dust', 'rocky'] },
      { w: 'Saturn', c: ['rings', 'planet', 'gas', 'giant', 'orbit'] },
      { w: 'Jupiter', c: ['giant', 'gas', 'planet', 'storm', 'spot'] },
      { w: 'Crater', c: ['hole', 'impact', 'moon', 'dent', 'round'] },
      { w: 'Gravity', c: ['pull', 'fall', 'force', 'weight', 'down'] },
      { w: 'Spaceship', c: ['fly', 'travel', 'crew', 'launch', 'orbit'] },
      { w: 'Constellation', c: ['stars', 'pattern', 'sky', 'shape', 'connect'] }
    ]),

    // ===================== more WORD packs (appended) =====================
    w('fruits', 'Fruits', 'Food & Drink', [
      { w: 'Apple', c: ['red', 'crunch', 'tree', 'core', 'pie'] },
      { w: 'Banana', c: ['yellow', 'peel', 'curve', 'monkey', 'soft'] },
      { w: 'Orange', c: ['citrus', 'peel', 'juice', 'segment', 'round'] },
      { w: 'Grapes', c: ['bunch', 'wine', 'small', 'vine', 'purple'] },
      { w: 'Strawberry', c: ['red', 'seeds', 'sweet', 'jam', 'tip'] },
      { w: 'Watermelon', c: ['summer', 'seeds', 'slice', 'green', 'big'] },
      { w: 'Pineapple', c: ['spiky', 'tropical', 'rings', 'crown', 'sour'] },
      { w: 'Mango', c: ['tropical', 'pit', 'sweet', 'orange', 'juicy'] },
      { w: 'Cherry', c: ['red', 'stem', 'small', 'pair', 'pit'] },
      { w: 'Peach', c: ['fuzzy', 'soft', 'pit', 'sweet', 'orange'] },
      { w: 'Lemon', c: ['sour', 'yellow', 'zest', 'juice', 'squeeze'] },
      { w: 'Kiwi', c: ['green', 'fuzzy', 'seeds', 'small', 'tangy'] },
      { w: 'Blueberry', c: ['tiny', 'blue', 'muffin', 'sweet', 'pie'] },
      { w: 'Pear', c: ['green', 'shape', 'sweet', 'tree', 'grainy'] },
      { w: 'Coconut', c: ['shell', 'tropical', 'milk', 'hard', 'palm'] }
    ]),
    w('vegetables', 'Vegetables', 'Food & Drink', [
      { w: 'Carrot', c: ['orange', 'rabbit', 'crunch', 'root', 'long'] },
      { w: 'Potato', c: ['fries', 'mash', 'root', 'brown', 'spud'] },
      { w: 'Tomato', c: ['red', 'sauce', 'round', 'salad', 'juicy'] },
      { w: 'Onion', c: ['layers', 'cry', 'smell', 'rings', 'sharp'] },
      { w: 'Broccoli', c: ['green', 'tree', 'healthy', 'floret', 'steam'] },
      { w: 'Cucumber', c: ['green', 'cool', 'salad', 'slice', 'long'] },
      { w: 'Pepper', c: ['spicy', 'bell', 'colour', 'crunch', 'hot'] },
      { w: 'Corn', c: ['cob', 'yellow', 'kernel', 'butter', 'pop'] },
      { w: 'Spinach', c: ['green', 'leaf', 'iron', 'salad', 'wilt'] },
      { w: 'Pumpkin', c: ['orange', 'Halloween', 'carve', 'pie', 'big'] },
      { w: 'Lettuce', c: ['leaf', 'salad', 'green', 'crisp', 'wrap'] },
      { w: 'Garlic', c: ['clove', 'smell', 'cook', 'breath', 'white'] },
      { w: 'Mushroom', c: ['fungus', 'cap', 'forest', 'pizza', 'umbrella'] },
      { w: 'Peas', c: ['green', 'pod', 'small', 'round', 'roll'] }
    ]),
    w('ocean', 'Sea Creatures', 'Nature', [
      { w: 'Shark', c: ['teeth', 'fin', 'jaws', 'hunt', 'fear'] },
      { w: 'Dolphin', c: ['smart', 'jump', 'grey', 'friendly', 'flip'] },
      { w: 'Whale', c: ['huge', 'spout', 'blue', 'song', 'deep'] },
      { w: 'Octopus', c: ['eight', 'ink', 'arms', 'suckers', 'squish'] },
      { w: 'Crab', c: ['claws', 'shell', 'sideways', 'pinch', 'beach'] },
      { w: 'Jellyfish', c: ['sting', 'float', 'clear', 'tentacle', 'wobble'] },
      { w: 'Starfish', c: ['five', 'star', 'rock', 'slow', 'arms'] },
      { w: 'Seahorse', c: ['curl', 'tiny', 'tail', 'upright', 'cute'] },
      { w: 'Lobster', c: ['claws', 'red', 'shell', 'dinner', 'tail'] },
      { w: 'Turtle', c: ['shell', 'slow', 'swim', 'flipper', 'old'] },
      { w: 'Squid', c: ['ink', 'tentacle', 'fast', 'soft', 'deep'] },
      { w: 'Stingray', c: ['flat', 'glide', 'tail', 'sting', 'sand'] },
      { w: 'Coral', c: ['reef', 'colour', 'hard', 'grow', 'tropical'] },
      { w: 'Eel', c: ['long', 'slippery', 'electric', 'hide', 'snake'] }
    ]),
    w('birds', 'Birds', 'Nature', [
      { w: 'Eagle', c: ['fly', 'talon', 'soar', 'sharp', 'proud'] },
      { w: 'Penguin', c: ['waddle', 'ice', 'tuxedo', 'cold', 'slide'] },
      { w: 'Owl', c: ['night', 'hoot', 'wise', 'eyes', 'turn'] },
      { w: 'Parrot', c: ['talk', 'colour', 'tropical', 'mimic', 'perch'] },
      { w: 'Flamingo', c: ['pink', 'leg', 'stand', 'curve', 'wade'] },
      { w: 'Peacock', c: ['feathers', 'fan', 'blue', 'show', 'proud'] },
      { w: 'Sparrow', c: ['small', 'brown', 'common', 'chirp', 'city'] },
      { w: 'Crow', c: ['black', 'caw', 'smart', 'scare', 'corn'] },
      { w: 'Swan', c: ['white', 'graceful', 'lake', 'neck', 'glide'] },
      { w: 'Robin', c: ['red', 'chest', 'garden', 'spring', 'worm'] },
      { w: 'Pelican', c: ['beak', 'pouch', 'fish', 'big', 'dive'] },
      { w: 'Woodpecker', c: ['peck', 'tree', 'tap', 'red', 'drill'] },
      { w: 'Ostrich', c: ['big', 'run', 'tall', 'neck', 'egg'] },
      { w: 'Hummingbird', c: ['tiny', 'hover', 'fast', 'wings', 'nectar'] }
    ]),
    w('instruments', 'Instruments', 'Music', [
      { w: 'Guitar', c: ['strings', 'strum', 'pick', 'band', 'chord'] },
      { w: 'Piano', c: ['keys', 'black', 'white', 'pedal', 'play'] },
      { w: 'Drums', c: ['beat', 'sticks', 'loud', 'rhythm', 'kit'] },
      { w: 'Violin', c: ['bow', 'strings', 'chin', 'classical', 'small'] },
      { w: 'Flute', c: ['blow', 'metal', 'holes', 'high', 'side'] },
      { w: 'Trumpet', c: ['brass', 'blow', 'valves', 'loud', 'jazz'] },
      { w: 'Saxophone', c: ['brass', 'reed', 'jazz', 'curve', 'blow'] },
      { w: 'Harp', c: ['strings', 'pluck', 'big', 'angel', 'gold'] },
      { w: 'Cello', c: ['big', 'bow', 'floor', 'low', 'strings'] },
      { w: 'Clarinet', c: ['reed', 'black', 'blow', 'holes', 'wood'] },
      { w: 'Banjo', c: ['strings', 'country', 'round', 'twang', 'pluck'] },
      { w: 'Tambourine', c: ['shake', 'jingle', 'round', 'hand', 'tap'] },
      { w: 'Xylophone', c: ['bars', 'mallet', 'tap', 'colour', 'tune'] },
      { w: 'Accordion', c: ['squeeze', 'buttons', 'fold', 'air', 'folk'] }
    ]),
    w('school', 'School', 'Everyday', [
      { w: 'Pencil', c: ['write', 'lead', 'sharp', 'eraser', 'wood'] },
      { w: 'Eraser', c: ['rub', 'mistake', 'pink', 'pencil', 'gone'] },
      { w: 'Notebook', c: ['pages', 'write', 'lines', 'spiral', 'class'] },
      { w: 'Backpack', c: ['carry', 'straps', 'books', 'shoulder', 'zip'] },
      { w: 'Ruler', c: ['measure', 'straight', 'inches', 'line', 'plastic'] },
      { w: 'Whiteboard', c: ['marker', 'wipe', 'class', 'write', 'wall'] },
      { w: 'Homework', c: ['assignment', 'home', 'due', 'study', 'task'] },
      { w: 'Recess', c: ['break', 'play', 'outside', 'free', 'fun'] },
      { w: 'Locker', c: ['metal', 'lock', 'hall', 'store', 'slam'] },
      { w: 'Calculator', c: ['numbers', 'buttons', 'math', 'screen', 'add'] },
      { w: 'Globe', c: ['round', 'world', 'spin', 'map', 'desk'] },
      { w: 'Chalk', c: ['board', 'white', 'dust', 'write', 'snap'] },
      { w: 'Exam', c: ['test', 'study', 'grade', 'nervous', 'paper'] },
      { w: 'Glue', c: ['stick', 'paste', 'craft', 'bond', 'white'] }
    ]),
    w('tools', 'Tools', 'Everyday', [
      { w: 'Hammer', c: ['nail', 'hit', 'metal', 'bang', 'handle'] },
      { w: 'Screwdriver', c: ['screw', 'turn', 'twist', 'flat', 'tip'] },
      { w: 'Wrench', c: ['bolt', 'turn', 'grip', 'metal', 'tight'] },
      { w: 'Drill', c: ['hole', 'spin', 'bit', 'power', 'bore'] },
      { w: 'Saw', c: ['cut', 'teeth', 'wood', 'blade', 'push'] },
      { w: 'Nail', c: ['hammer', 'sharp', 'metal', 'wood', 'small'] },
      { w: 'Pliers', c: ['grip', 'pinch', 'wire', 'squeeze', 'jaw'] },
      { w: 'Ladder', c: ['climb', 'steps', 'high', 'lean', 'rungs'] },
      { w: 'Level', c: ['flat', 'bubble', 'straight', 'check', 'line'] },
      { w: 'Chisel', c: ['carve', 'wood', 'sharp', 'tap', 'shape'] },
      { w: 'Bolt', c: ['nut', 'thread', 'tight', 'metal', 'turn'] },
      { w: 'Tape Measure', c: ['length', 'pull', 'inches', 'reel', 'measure'] },
      { w: 'Toolbox', c: ['carry', 'store', 'metal', 'tools', 'handle'] },
      { w: 'Sandpaper', c: ['rough', 'smooth', 'rub', 'grit', 'wood'] }
    ]),
    w('holidays', 'Holidays', 'Everyday', [
      { w: 'Christmas', c: ['tree', 'gift', 'snow', 'Santa', 'December'] },
      { w: 'Halloween', c: ['costume', 'candy', 'scary', 'pumpkin', 'October'] },
      { w: 'Birthday', c: ['cake', 'candles', 'gift', 'wish', 'party'] },
      { w: 'Easter', c: ['eggs', 'bunny', 'hunt', 'spring', 'basket'] },
      { w: 'New Year', c: ['midnight', 'countdown', 'fireworks', 'resolution', 'January'] },
      { w: 'Valentine', c: ['heart', 'love', 'red', 'rose', 'February'] },
      { w: 'Fireworks', c: ['bang', 'sky', 'colour', 'sparkle', 'night'] },
      { w: 'Wedding', c: ['marry', 'dress', 'ring', 'vows', 'cake'] },
      { w: 'Carnival', c: ['rides', 'parade', 'costume', 'music', 'crowd'] },
      { w: 'Picnic', c: ['blanket', 'basket', 'park', 'food', 'outside'] },
      { w: 'Parade', c: ['march', 'float', 'street', 'crowd', 'band'] },
      { w: 'Festival', c: ['music', 'crowd', 'food', 'stage', 'fun'] },
      { w: 'Costume', c: ['dress up', 'mask', 'pretend', 'wear', 'party'] },
      { w: 'Thanksgiving', c: ['turkey', 'family', 'feast', 'grateful', 'November'] }
    ]),
    w('superpowers', 'Superpowers', 'Fantasy', [
      { w: 'Flying', c: ['sky', 'wings', 'soar', 'up', 'cape'] },
      { w: 'Invisibility', c: ['unseen', 'hide', 'vanish', 'gone', 'sneak'] },
      { w: 'Telepathy', c: ['mind', 'read', 'thought', 'silent', 'sense'] },
      { w: 'Super Strength', c: ['lift', 'powerful', 'crush', 'muscle', 'heavy'] },
      { w: 'Super Speed', c: ['fast', 'blur', 'run', 'quick', 'flash'] },
      { w: 'Teleport', c: ['blink', 'appear', 'instant', 'gone', 'jump'] },
      { w: 'Healing', c: ['cure', 'mend', 'recover', 'wound', 'restore'] },
      { w: 'Shapeshift', c: ['change', 'form', 'morph', 'disguise', 'become'] },
      { w: 'Time Travel', c: ['past', 'future', 'clock', 'rewind', 'jump'] },
      { w: 'Mind Control', c: ['command', 'obey', 'puppet', 'will', 'force'] },
      { w: 'Force Field', c: ['shield', 'block', 'bubble', 'protect', 'wall'] },
      { w: 'X-ray Vision', c: ['see through', 'eyes', 'inside', 'bones', 'wall'] },
      { w: 'Telekinesis', c: ['move', 'mind', 'lift', 'float', 'objects'] },
      { w: 'Fire Breath', c: ['flame', 'mouth', 'burn', 'dragon', 'hot'] }
    ]),
    w('careers', 'Jobs II', 'People', [
      { w: 'Astronaut', c: ['space', 'rocket', 'suit', 'orbit', 'float'] },
      { w: 'Firefighter', c: ['hose', 'flame', 'truck', 'rescue', 'ladder'] },
      { w: 'Veterinarian', c: ['animals', 'pet', 'cure', 'clinic', 'paw'] },
      { w: 'Electrician', c: ['wire', 'power', 'socket', 'fix', 'shock'] },
      { w: 'Plumber', c: ['pipe', 'leak', 'water', 'fix', 'wrench'] },
      { w: 'Architect', c: ['design', 'building', 'plan', 'draw', 'blueprint'] },
      { w: 'Detective', c: ['clue', 'solve', 'crime', 'mystery', 'search'] },
      { w: 'Librarian', c: ['books', 'quiet', 'shelf', 'borrow', 'stamp'] },
      { w: 'Mechanic', c: ['car', 'engine', 'fix', 'oil', 'tools'] },
      { w: 'Photographer', c: ['camera', 'snap', 'photo', 'lens', 'pose'] },
      { w: 'Scientist', c: ['lab', 'experiment', 'study', 'coat', 'test'] },
      { w: 'Carpenter', c: ['wood', 'build', 'saw', 'nail', 'craft'] },
      { w: 'Surgeon', c: ['operate', 'scalpel', 'hospital', 'careful', 'mask'] },
      { w: 'Tailor', c: ['sew', 'fabric', 'fit', 'needle', 'suit'] }
    ]),

    // ===================== more PAIR packs (Undercover) =====================
    pr('pairs_jobs', 'Jobs (pairs)', 'People', [
      { a: 'Doctor', b: 'Nurse' }, { a: 'Chef', b: 'Baker' }, { a: 'Pilot', b: 'Sailor' },
      { a: 'Teacher', b: 'Professor' }, { a: 'Singer', b: 'Rapper' }, { a: 'Painter', b: 'Sculptor' },
      { a: 'Waiter', b: 'Bartender' }, { a: 'Farmer', b: 'Rancher' }, { a: 'Author', b: 'Journalist' },
      { a: 'Barber', b: 'Hairdresser' }, { a: 'Magician', b: 'Clown' }, { a: 'Lawyer', b: 'Judge' }
    ]),
    pr('pairs_clothing', 'Clothing (pairs)', 'Everyday', [
      { a: 'Jacket', b: 'Coat' }, { a: 'Shirt', b: 'Blouse' }, { a: 'Pants', b: 'Jeans' },
      { a: 'Hat', b: 'Cap' }, { a: 'Shoes', b: 'Boots' }, { a: 'Scarf', b: 'Shawl' },
      { a: 'Sweater', b: 'Hoodie' }, { a: 'Dress', b: 'Gown' }, { a: 'Gloves', b: 'Mittens' },
      { a: 'Sandals', b: 'Slippers' }, { a: 'Tie', b: 'Bowtie' }, { a: 'Vest', b: 'Cardigan' }
    ]),
    pr('pairs_emotions', 'Feelings (pairs)', 'Abstract', [
      { a: 'Happy', b: 'Excited' }, { a: 'Sad', b: 'Lonely' }, { a: 'Angry', b: 'Annoyed' },
      { a: 'Scared', b: 'Nervous' }, { a: 'Tired', b: 'Sleepy' }, { a: 'Calm', b: 'Relaxed' },
      { a: 'Proud', b: 'Confident' }, { a: 'Shy', b: 'Embarrassed' }, { a: 'Brave', b: 'Bold' },
      { a: 'Glad', b: 'Cheerful' }, { a: 'Worried', b: 'Anxious' }, { a: 'Surprised', b: 'Shocked' }
    ]),
    pr('pairs_vehicles', 'Vehicles (pairs)', 'Things', [
      { a: 'Car', b: 'Truck' }, { a: 'Boat', b: 'Ship' }, { a: 'Bicycle', b: 'Motorcycle' },
      { a: 'Plane', b: 'Helicopter' }, { a: 'Bus', b: 'Van' }, { a: 'Train', b: 'Tram' },
      { a: 'Scooter', b: 'Skateboard' }, { a: 'Jet', b: 'Rocket' }, { a: 'Taxi', b: 'Limo' },
      { a: 'Canoe', b: 'Kayak' }, { a: 'Submarine', b: 'Yacht' }, { a: 'Ambulance', b: 'Fire Truck' }
    ])
  ];

  return { packs: PACKS };
});
